[build]
  base = "frontend"
  command = "flutter pub get && flutter build web --release --base-href / --dart-define=API_BASE_URL=${API_BASE_URL}"
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
